#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "minchat"
name = "Minchat"
description.en = "Minimalist web chat"
description.fr = "Web chat minimaliste"

version = "2017.05.30~ynh1"

maintainers = ["chtixof"]

[upstream]
license = "MIT"
code = "https://github.com/wojtek77/chat"

[integration]
yunohost = ">=11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "10M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/minchat"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/wojtek77/chat/archive/368fdb3451e1c46b530dc239d9ce522edc6fb812.tar.gz"
    sha256 = "f1809fea5d7eed3d0dbac9715e3f756bd710d08ee8060008f8ca285e03fe04eb"

    autoupdate.strategy = "latest_github_commit"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-fpm",
    ]
