#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source app helpers
source ./_common
source /usr/share/yunohost/helpers

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

CHECK_VAR "$app" "app name not set"

CHECK_PATH

CHECK_DOMAINPATH

CHECK_FINALPATH

# Create system user dedicace for this app
ynh_system_user_create $app

# Copy files to the right place
final_path=/var/www/$app
sudo mkdir -p $final_path
extract_source $final_path

# Copy files to the right place with the right permissions
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo chown -R $app: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
ynh_nginx_config

# Create the php-fpm pool config
ynh_fpm_config

# Set ssowat config
if [ $is_public -eq 0 ]
then
	ynh_app_setting_delete $app skipped_uris # Delete public access
fi

if [ $is_public -eq 1 ]
then
	ynh_app_setting_set $app skipped_uris "/" # Make app public if necessary
fi

sudo systemctl reload nginx
sudo yunohost app ssowatconf