#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -eu

if [ ! -e _common ]; then
	# Get file fonction if not been to the current directory
	sudo cp ../settings/scripts/_common ./_common
	sudo chmod a+rx _common
fi
# Loads the generic functions usually used in the script
source _common
# Source app helpers
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
user=$(ynh_app_setting_get $app allowed_users)
is_public=$(ynh_app_setting_get $app is_public)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Check $final_path
final_path="/var/www/${app}"
if [ -d $final_path ]; then
	ynh_die "There is already a directory: $final_path"
fi

# Check configuration files
nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
if [ -f $nginx_conf ]; then
	ynh_die "The NGINX configuration already exists at '${nginx_conf}'. 
	You should safely delete it before restoring this app."
fi
# Check configuration files php-fpm
phpfpm_conf="/etc/php5/fpm/pool.d/php-fpm-${app}.conf"
if [ -f $phpfpm_conf ]; then 
	ynh_die "The PHP FPM configuration already exists at '${phpfpm_conf}'. 
	You should safely delete it before restoring this app."
fi

phpfpm_ini="/etc/php5/fpm/conf.d/20-${app}.ini"
if [ -f $phpfpm_ini ]; then
	ynh_die "The PHP FPM INI configuration already exists at '${phpfpm_ini}'. 
	You should safely delete it before restoring this app."
fi

# Create system user dedicace for this app
ynh_system_user_create $app

# Restore sources & data
sudo cp -a "./sources" $final_path

# Set permissions
sudo chown -R $app: $final_path

# Restore configuration files
sudo cp -a ./conf/nginx.conf "${nginx_conf}"

# Restore php-fpm configuration files
sudo cp -a ./conf/php-fpm.conf "${phpfpm_conf}"
sudo cp -a ./conf/php-fpm.ini "${phpfpm_ini}"

# Set ssowat config
if [[ $is_public -eq 0 ]]; then
	ynh_app_setting_delete $app skipped_uris
fi

# Reload service
sudo systemctl reload nginx
sudo yunohost app ssowatconf